version: "3.9"

services:
  okx-dashboard:
    build: .
    container_name: RealTime_Trade_dashboard_app
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_PORT=8501
    volumes:
      - .:/app
    restart: unless-stopped
